name: Check Shell Command

on: [push]

jobs:
  run-shell-commdsfasfand:
    runs-on: ubuntu-latest
    steps:
      - name: get uname -a
        run: uname -a

      - name: get public ip address
        run: curl ifconfig.cc

      - name: get hostname
        run: hostname
      
      - name: get df -hT
        run: df -hT

      - name: list file in the current working folder
        run: ls -lrth
  
  run-shel-on-windows:
    runs-on: windows-latest
    steps:
      - name: Get current directory
        run: Get-Location

      - name: Get current directory by using Bash
        run: pwd
        shell: bash